###
# _config.dev.yml
#
# Dev only config settings, not automatically applied unless starting Jekyll via `yarn start`
# See package.json scripts for details of command
#
###
incremental: False
env: development
issue_app_url: 'http://localhost:5000/'
