###
# _config.yml
#
# Jekyll configuration
#
#
###
# Build
###
source: src
destination: dist
timezone: Europe/London
lang: en_GB
permalink: pretty
env: production
exclude: ['_templates']

###
# Meta
#
###
url: https://theodi.github.io
baseurl: /open-standards-guidebook # @todo update for live
name: Open Standards for Data Guidebook

issue_app_url: 'https://open-standards-guidebook.herokuapp.com/'

###
# Social / SEO
# see: https://github.com/jekyll/jekyll-seo-tag/blob/46ad253d4de8d8064b4156a9db530399bdd9ec11/docs/usage.md
# for detailed docs
###
twitter:
  username: ODIHQ

# @todo update pre live
# facebook:
#  app_id: 1234 # App ID for Facebook insights
#  publisher: 1234 # - a Facebook page URL or ID of the publishing entity
#  admins: 1234 # - a Facebook user ID for domain insights linked to a personal account

# @todo update pre live
# # Verify website ownership
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

description: This is the default site description, change me # @todo update pre live
title_image: ''
ga: 'UA-XXXXXXXX-X' # @todo update pre live

###
# Default front matter
#
# This allows us to not have to set these value in every page template
###

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: content-page
      nav:
        order: 1000
      show_toc: true
      show_nav: true
      show_intro_sentence: true
