title: "Resource Listing Layout"
status: "ready"

context:
  # Hero Context
  hero:
    heading: Open Standards Organisations
    sidenav: true

  # Hero Lede
  lede:
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar ex pretium interdum gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere.'

  # Nav Context
  nav:
    modifier: m-nav--large
    items:
    -
      title: What are Open Standards for Data?
    -
      title: Types of Open Data Standards
    -
      title: Why use Open Standards for Data

  # Nav Meta Title
  metatitle:
    message: Getting started

  # Section Listings
  sections:
    items:
    -
      title: Creating Open Standards
      meta: Process

      # Items within this Section Listing
      items:
      -
        title: Scoping & Starting
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Developing standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Governance and guidance
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Impact of Open Standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
    -
      title: Open Standards and you
      meta: Groups

      # Items within this Section Listing
      items:
      -
        title: Organisations developing standards
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Policy specialists
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Domain experts
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.
      -
        title: Data publishers and consumers
        description: Short description nulla eu molestie massa. Pellentesque fermentum urna pretium nulla lacinia gravida. Aenean in aliquet mauris.


