title: "Podcast Layout"
status: "ready"

context:
  # Hero Context
  hero:
    lowernav: true

  # Hero Lede
  lede:
    message: 'Some introductory text lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vulputate magna velit. Vestibulum fermentum fermentum libero. Vestibulum dui dui, pulvinar bibendum nulla eget, lacinia fermentum lorem.'

  # Nav Context
  nav:
    pill: true
    modifier: m-nav--large
    items:
    -
      title: What are Open Standards for Data?
    -
      title: Types of Open Data Standards
    -
      title: Why use Open Standards for Data

  # Nav Title
  navTitle: Introduction to Open Standards

